import { test, expect } from "@playwright/test";
import HomePage from "../../pom/HomePage";
import RegisterPage from "../../pom/RegisterPage";
import BankHelper from "../../pom/BankHelper";
import data from "../../data/data.json";
test("Transfer Confirmation Message Content", async ({ page, request }) => {
    const home = new HomePage(page);
    const register = new RegisterPage(page);
    const bank = new BankHelper(page, request);
    await home.goto(data[0].url);
    await home.clickRegister();
    await register.register(data[0]);
    await expect(page.locator('//div[@id="rightPanel"]/p')).toHaveText('Your account was created successfully. You are now logged in.');
    let destinationAccountId = await bank.openNewAccount('0');
    console.log('Destination Account ID:', destinationAccountId);
    await bank.transferFunds(data[0].amount, destinationAccountId);
    console.log('Transfer done');
    let confirmationText = await page.locator('#showResult').innerText();
    console.log('Confirmation Message:', confirmationText);
    expect(confirmationText).toContain(data[0].amount);
    expect(confirmationText).toContain(destinationAccountId);
});
test("Validate Source Account Balance Deducted via API", async ({ page, request }) => {
    const home = new HomePage(page);
    const register = new RegisterPage(page);
    const bank = new BankHelper(page, request);
    await home.goto(data[0].url);
    await home.clickRegister();
    await register.register(data[0]);
    await expect(page.locator('//div[@id="rightPanel"]/p')).toHaveText('Your account was created successfully. You are now logged in.');
    let sourceAccountId = await bank.getFirstAccountId();
    console.log('Source Account ID:', sourceAccountId);
    let destinationAccountId = await bank.openNewAccount('0');
    console.log('Destination Account ID:', destinationAccountId);
    let balanceBefore = await bank.getAccountBalance(sourceAccountId);
    console.log('Source Balance Before Transfer:', balanceBefore);
    await bank.transferFunds(data[0].amount, destinationAccountId);
    console.log('Transfer done successfully');
    let balanceAfter = await bank.getAccountBalance(sourceAccountId);
    console.log('Source Balance After Transfer:', balanceAfter);
    let transferAmount = Number(data[0].amount);
    let expectedBalance = balanceBefore - transferAmount;
    console.log('Transfer Amount:', transferAmount);
    console.log('Expected Balance:', expectedBalance);
    console.log('Actual Balance:', balanceAfter);
    expect(balanceAfter).toBe(expectedBalance);
});
test("Validate Total Balance Conservation After Transfer", async ({ page, request }) => {
    const home = new HomePage(page);
    const register = new RegisterPage(page);
    const bank = new BankHelper(page, request);
    await home.goto(data[0].url);
    await home.clickRegister();
    await register.register(data[0]);
    await expect(page.locator('//div[@id="rightPanel"]/p')).toHaveText('Your account was created successfully. You are now logged in.');
    let sourceAccountId = await bank.getFirstAccountId();
    console.log('Source Account ID:', sourceAccountId);
    let destinationAccountId = await bank.openNewAccount('0');
    console.log('Destination Account ID:', destinationAccountId);
    let sourceBalanceBefore = await bank.getAccountBalance(sourceAccountId);
    let destBalanceBefore = await bank.getAccountBalance(destinationAccountId);
    let totalBefore = sourceBalanceBefore + destBalanceBefore;
    console.log('Source Balance Before:', sourceBalanceBefore);
    console.log('Destination Balance Before:', destBalanceBefore);
    console.log('Total Balance Before:', totalBefore);
    await bank.transferFunds(data[0].amount, destinationAccountId);
    console.log('Transfer done successfully');
    let sourceBalanceAfter = await bank.getAccountBalance(sourceAccountId);
    let destBalanceAfter = await bank.getAccountBalance(destinationAccountId);
    let totalAfter = sourceBalanceAfter + destBalanceAfter;
    console.log('Source Balance After:', sourceBalanceAfter);
    console.log('Destination Balance After:', destBalanceAfter);
    console.log('Total Balance After:', totalAfter);
    expect(totalAfter).toBe(totalBefore);
});